/*
	SYM.NAME Indexes
*/
CREATE INDEX Address_Index
ON SYM.NAME (STREET, CITY, STATE, ZIPCODE);

CREATE INDEX Name_Index
ON SYM.NAME (TITLE, FIRST, MIDDLE, LAST, SUFFIX);

CREATE INDEX SSN_Index
ON SYM.NAME (SSN);

CREATE INDEX ParentAcct_Index
ON SYM.NAME (PARENTACCOUNT);

CREATE INDEX Ordinal_Index
ON SYM.NAME (ORDINAL);

/* 
	SYM.ACCOUNT Indexes
*/
CREATE INDEX ClosDeate_Index
ON SYM.ACCOUNT (CLOSEDATE);

CREATE INDEX AccountNum_Index
ON SYM.ACCOUNT (ACCOUNTNUMBER);