/*
	UpdateLinkCardTransaction.sql

	Michael McRae
	July 21, 2014

	
*/
-- This connects Loan Transactions to a Credit Card
-- INSERT INTO Link_Card_Transaction(CARD_SQN, TRANSACTION_SQN, LINK_CARD_TRANSACTION_RSRC)
SELECT A.HUB_CARD_SQN, B.HUB_TRANSACTION_SQN, 'EASE' AS LINK_CARD_TRANSACTION_RSRC
FROM sym_vault1.Hub_Card A
	JOIN sym_vault1.Hub_Transaction B
		ON A.PARENT_ACCT = B.PARENT_ACCT
WHERE B.CATEGORY = 'L' AND B.SOURCE_CODE = 'G' AND
		(A.CHK_ID = '' AND SAV_ID = '') AND A.CREDIT_ID = B.ID;
/*
INSERT INTO Link_Card_Transaction(CARD_SQN, TRANSACTION_SQN, LINK_CARD_TRANSACTION_RSRC)
SELECT A.HUB_CARD_SQN, B.HUB_TRANSACTION_SQN, 'EASE' AS LINK_CARD_TRANSACTION_RSRC
FROM sym_vault1.Hub_Card A
	JOIN sym_vault1.Hub_Transaction B
		ON A.PARENT_ACCT = B.PARENT_ACCT
WHERE  B.CATEGORY = 'S' AND B.SOURCE_CODE = 'G' AND
		A.CREDIT_ID = '' AND (A.SAV_ID = B.ID OR A.CHK_ID = B.ID);
*/