SELECT PARENTACCOUNT TITLE, FIRST, MIDDLE, LAST, SUFFIX, STREET, CITY, STATE, ZIPCODE, count(*)
FROM SYM.NAME
GROUP BY PARENTACCOUNT, TITLE, FIRST, MIDDLE, LAST, SUFFIX, STREET, CITY, STATE, ZIPCODE
HAVING count(*) > 1;