SELECT PARENTACCOUNT, TITLE, FIRST, MIDDLE, LAST, SUFFIX, STREET, CITY, STATE, ZIPCODE
FROM SYM.NAME
WHERE FIRST = 'AMANDA' AND MIDDLE = 'R' AND LAST = 'FRANKLIN' AND STREET = '1604 110TH AVENUE' AND CITY ='MILAN' AND STATE = 'IL' AND ZIPCODE = '61264';