SELECT A.LNG, A.LAT, C.STREET, C.CITY, C.STATE, C.ZIPCODE, count(*) AS 'NUM OF PRODUCT INSTANCES'
FROM
sym_vault1.Stage_Bing_AddressLngLat A
	JOIN sym_vault1.Link_Addr_ProductInstance B
		ON A.ADDR_SQN = B.ADDR_SQN
	JOIN sym_vault1.Hub_Address C
		ON A.ADDR_SQN = C.HUB_ADDRESS_SQN
	LEFT JOIN sym_vault1.Sat_ProductInstance_Closed D
		ON B.PRODUCTINSTANCE_SQN = D.PRODUCTINSTANCE_SQN
WHERE C.STATE = 'IA' AND C.CITY <> 'ROCK ISLAND' AND C.CITY <> 'MOLINE' AND D.PRODUCTINSTANCE_SQN IS NULL
GROUP BY B.ADDR_SQN