SELECT A.ADDR_SQN, B.STREET, B.CITY, B.STATE, B.ZIPCODE, D.HUB_PRODUCT_INSTANCE_SQN, D.PARENT_ACCT, D.ID, E.TYPE, D.CATEGORY
FROM sym_vault1.Link_Addr_ProductInstance A
	JOIN sym_vault1.Hub_Address B
		ON A.ADDR_SQN = B.HUB_ADDRESS_SQN
	JOIN sym_vault1.Hub_Product_Instance D
		ON A.PRODUCTINSTANCE_SQN = D.HUB_PRODUCT_INSTANCE_SQN
	JOIN sym_vault1.Sat_ProductInstance_Type E
		ON D.HUB_PRODUCT_INSTANCE_SQN = E.PRODUCTINSTANCE_SQN
	LEFT JOIN sym_vault1.Sat_ProductInstance_Closed C
		ON A.PRODUCTINSTANCE_SQN = C.PRODUCTINSTANCE_SQN
WHERE C.PRODUCTINSTANCE_SQN IS NULL;