SELECT TITLE, FIRST, MIDDLE, LAST, SUFFIX, SSN, OPENDATE FROM SYM.NAME
JOIN
(SELECT ACCOUNTNUMBER, OPENDATE, 'EASE' AS HUB_ACCT_RSRC FROM SYM.ACCOUNT A
LEFT JOIN
sym_vault1.Hub_Account B
ON A.ACCOUNTNUMBER = B.ACCT_NUM
WHERE B.ACCT_NUM IS NULL AND A.CLOSEDATE = '0000-00-00') C
ON NAME.PARENTACCOUNT = C.ACCOUNTNUMBER;