select
	DISTINCT A.ACCT_NUM
from Hub_Account A
	JOIN Hub_Product_Instance B
		ON A.ACCT_NUM = B.PARENT_ACCT
WHERE A.OPEN_DATE = B.OPEN_DATE AND B.CATEGORY = 'S' AND B.ID <> '00' AND A.OPEN_DATE > '2014-06-30'
		AND A.ACCT_NUM IN (
select
	DISTINCT ACCT_NUM
from Hub_Account A
	JOIN Hub_Product_Instance B
		ON A.ACCT_NUM = B.PARENT_ACCT
WHERE A.OPEN_DATE = B.OPEN_DATE AND B.CATEGORY = 'L' AND A.OPEN_DATE > '2014-06-30')