SELECT A.LINK_PERSON_PRODUCTINSTANCE_SQN, A.PERSON_SQN, B.SSN, C.PARENT_ACCT, C.ID, E.TYPE, E.NAME, C.CATEGORY
FROM sym_vault1.Link_Person_ProductInstance A
	JOIN sym_vault1.Hub_Person B
		ON A.PERSON_SQN = B.HUB_PERSON_SQN
	JOIN sym_vault1.Hub_Product_Instance C
		ON A.PRODUCTINSTANCE_SQN = C.HUB_PRODUCT_INSTANCE_SQN
	JOIN sym_vault1.Link_Product_ProductInstance D
		ON C.HUB_PRODUCT_INSTANCE_SQN = D.PRODUCTINSTANCE_SQN
	JOIN sym_vault1.Hub_Product E
		ON D.PRODUCT_SQN = E.HUB_PRODUCT_SQN
WHERE B.SSN = 326889183